In [3]:
import glob                         # libreria que permite buscar varios archivos de un mismo tipo
import pandas as pd                 # libreria de pandas para manipular archivos y dataframes
import xml.etree.ElementTree as ET  # Libreria para procesar archivos xml.
from datetime import datetime

tmpfile    = "temp.tmp"               # archivo para almacenar los datos
logfile    = "logfile.txt"            # todos los registros de eventos se almacenarán en este archivo
targetfile = "transformed_data.csv"   # Archivo donde se alamacena los datos transformados

def extract_from_csv(file_to_process):         #funcion que lee archivo de tipo csv y lo muestra como dataframe
    dataframe = pd.read_csv(file_to_process)
    return dataframe

def extract_from_json(file_to_process):
    dataframe = pd.read_json(file_to_process,lines=True)  #funcion que lee archivo de tipo json y lo muestra como dataframe
    return dataframe

def extract_from_xml(file_to_process):
    dataframe = pd.DataFrame(columns=["name", "height", "weight"])  #funcion que lee archivo de tipo xml y lo muestra como dataframe
    tree = ET.parse(file_to_process)
    root = tree.getroot()
    for person in root:
        name = person.find("name").text
        height = float(person.find("height").text)
        weight = float(person.find("weight").text)
        dataframe = dataframe.append({"name":name, "height":height, "weight":weight}, ignore_index=True)
    return dataframe

def extract():
    extracted_data = pd.DataFrame(columns=['name','height','weight']) # se crea un dataframe vacio con los nombres de columnas
    
    #process all csv files
    for csvfile in glob.glob("*.csv"):
        extracted_data = extracted_data.append(extract_from_csv(csvfile), ignore_index=True)  #se itera dentro del dataframe vacio y se agregan los datos de los archivos tipo csv 
        
        
    #process all json files
    for jsonfile in glob.glob("*.json"):
        extracted_data = extracted_data.append(extract_from_json(jsonfile), ignore_index=True) #se itera dentro del dataframe vacio y se agregan los datos de los archivos tipo json
    
    #process all xml files
    for xmlfile in glob.glob("*.xml"):
        extracted_data = extracted_data.append(extract_from_xml(xmlfile), ignore_index=True) #se itera dentro del dataframe vacio y se agregan los datos de los archivos tipo xml
        
    return extracted_data #retorna dataframe llenado con los datos en orden de formato (csv,json,xml)

print("Extract phase Started")
extracted_data = extract()
print("Extract phase Ended")  #se ejecuta funcion principal y muestra resultado
extracted_data

Extract phase Started
Extract phase Ended

C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:34: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  extracted_data = extracted_data.append(extract_from_csv(csvfile), ignore_index=True)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:34: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  extracted_data = extracted_data.append(extract_from_csv(csvfile), ignore_index=True)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:34: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  extracted_data = extracted_data.append(extract_from_csv(csvfile), ignore_index=True)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:34: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  extracted_data = extracted_data.append(extract_from_csv(csvfile), ignore_index=True)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:38: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  extracted_data = extracted_data.append(extract_from_json(jsonfile), ignore_index=True)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:38: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  extracted_data = extracted_data.append(extract_from_json(jsonfile), ignore_index=True)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:38: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  extracted_data = extracted_data.append(extract_from_json(jsonfile), ignore_index=True)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataframe = dataframe.append({"name":name, "height":height, "weight":weight}, ignore_index=True)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataframe = dataframe.append({"name":name, "height":height, "weight":weight}, ignore_index=True)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataframe = dataframe.append({"name":name, "height":height, "weight":weight}, ignore_index=True)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataframe = dataframe.append({"name":name, "height":height, "weight":weight}, ignore_index=True)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  extracted_data = extracted_data.append(extract_from_xml(xmlfile), ignore_index=True)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataframe = dataframe.append({"name":name, "height":height, "weight":weight}, ignore_index=True)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataframe = dataframe.append({"name":name, "height":height, "weight":weight}, ignore_index=True)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataframe = dataframe.append({"name":name, "height":height, "weight":weight}, ignore_index=True)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataframe = dataframe.append({"name":name, "height":height, "weight":weight}, ignore_index=True)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  extracted_data = extracted_data.append(extract_from_xml(xmlfile), ignore_index=True)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataframe = dataframe.append({"name":name, "height":height, "weight":weight}, ignore_index=True)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataframe = dataframe.append({"name":name, "height":height, "weight":weight}, ignore_index=True)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataframe = dataframe.append({"name":name, "height":height, "weight":weight}, ignore_index=True)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:26: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataframe = dataframe.append({"name":name, "height":height, "weight":weight}, ignore_index=True)
C:\Users\USUARIO\AppData\Local\Temp\ipykernel_5808\1446000635.py:42: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  extracted_data = extracted_data.append(extract_from_xml(xmlfile), ignore_index=True)

     name  height  weight Unnamed: 0
0    alex   65.78  112.99        NaN
1    ajay   71.52  136.49        NaN
2   alice   69.40  153.03        NaN
3    ravi   68.22  142.34        NaN
4     joe   67.79  144.30        NaN
5    alex   65.78  112.99        NaN
6    ajay   71.52  136.49        NaN
7   alice   69.40  153.03        NaN
8    ravi   68.22  142.34        NaN
9     joe   67.79  144.30        NaN
10   alex   65.78  112.99        NaN
11   ajay   71.52  136.49        NaN
12  alice   69.40  153.03        NaN
13   ravi   68.22  142.34        NaN
14    joe   67.79  144.30        NaN
15   jack   68.70  123.30        NaN
16    tom   69.80  141.49        NaN
17  tracy   70.01  136.46        NaN
18   john   67.90  112.37        NaN
19   jack   68.70  123.30        NaN
20    tom   69.80  141.49        NaN
21  tracy   70.01  136.46        NaN
22   john   67.90  112.37        NaN
23   jack   68.70  123.30        NaN
24    tom   69.80  141.49        NaN
25  tracy   70.01  136.46        NaN
26   john   67.90  112.37        NaN
27  simon   67.90  112.37        NaN
28  jacob   66.78  120.67        NaN
29  cindy   66.49  127.45        NaN
30   ivan   67.62  114.14        NaN
31  simon   67.90  112.37        NaN
32  jacob   66.78  120.67        NaN
33  cindy   66.49  127.45        NaN
34   ivan   67.62  114.14        NaN
35  simon   67.90  112.37        NaN
36  jacob   66.78  120.67        NaN
37  cindy   66.49  127.45        NaN
38   ivan   67.62  114.14        NaN